# https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/rel_21-11.html#rel_21-11
# Ubuntu : 20.04
# CUDA   : 11.4.1
# cuDNN  : 8.2.2.26
# Python : 3.8
# Tensorflow : 2.5.0

FROM nvcr.io/nvidia/tensorflow:21.08-tf2-py3

# 環境変数
# ENV http_proxy 'http://id:pass@proxy:port' など

# コマンド実行
# RUN apt-get update && apt-get upgrade -y  など