version: '3.2'
services:

  # バージョンごとにサービスを追加する
  # tensorflow 2.6.0
  tf260:

    # Dockerfile の場所
    # コンテキストは tf260 を指定しない
    # （tf260をコンテキストにするとDockerfileで親ディレクトリにある requirements.txt がコピーできない ）
    build:
      context: .  
      dockerfile: tf260/Dockerfile
    
    # devcontainer.json で決めたコンテナ名
    container_name: 'container_tf260'

    # コンテナの正常終了を防ぐ（コンテナ側に仮想端末を設置し、コンテナを持続させる）
    tty: true

    # ローカルファイルのマウント
    # 左がローカルファイルの場所, 右がコンテナ上の場所
    volumes: 
      - ../work:/work

    # GPUの設定
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


  # tensorflow x.x.x
  #tfxxx:
