# https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/rel_22-04.html#rel_22-04
# Ubuntu : 20.04
# CUDA   : 11.6.2
# cuDNN  : 8.4.0.27
# Python : 3.8
# Tensorflow : 2.8.0

FROM nvcr.io/nvidia/tensorflow:22.04-tf2-py3

# 環境変数
# ENV http_proxy 'http://id:pass@proxy:port' など

# コマンド実行
# RUN apt-get update && apt-get upgrade -y  など